### PR TITLE
[WIP] RYA-284: updated to support the use of bloom filter

### PR DESCRIPTION
**Pull request by DLotts**
## Description
Updated dao/accumulo.rya to support the use of bloom filter

### Tests
no new tests

### Links
[JIRA -> RYA-284](https://issues.apache.org/jira/browse/RYA-284)

### Checklist
- [ ] Code Review
- [ ] Squash Commits

#### People To Reivew
@meiercaleb , @pujav65 , @amihalik  anyone interested in Accumulo Bloom filters

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/<h2>Failed Tests: <span class='status-failure'>15</span></h2><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.indexing' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.indexing/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.indexing</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.indexing/testReport/org.apache.rya.indexing.statement.metadata/AccumuloStatementMetadataNodeTest/simpleQueryWithVariableContextAndJoinOnContext/'><strong>org.apache.rya.indexing.statement.metadata.AccumuloStatementMetadataNodeTest.simpleQueryWithVariableContextAndJoinOnContext</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.indexing/testReport/org.apache.rya.indexing.statement.metadata/AccumuloStatementMetadataNodeTest/simpleQueryWithConstantContext/'><strong>org.apache.rya.indexing.statement.metadata.AccumuloStatementMetadataNodeTest.simpleQueryWithConstantContext</strong></a></li></ul><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.sail' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.sail</a>: <span class='status-failure'>13</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testSimpleMergeJoinMultiWay/'><strong>org.apache.rya.MergeJoinTest.testSimpleMergeJoinMultiWay</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testMergeJoinMultiWay/'><strong>org.apache.rya.MergeJoinTest.testMergeJoinMultiWay</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testSimpleMergeJoin/'><strong>org.apache.rya.MergeJoinTest.testSimpleMergeJoin</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreConnectionTest/testNamedGraphLoad/'><strong>org.apache.rya.RdfCloudTripleStoreConnectionTest.testNamedGraphLoad</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreConnectionTest/testSPOObjRange/'><strong>org.apache.rya.RdfCloudTripleStoreConnectionTest.testSPOObjRange</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testHeartbeatCounts/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testHeartbeatCounts</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testEventsBtwnSystems/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testEventsBtwnSystems</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testAllEvents/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testAllEvents</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testEventsForUri/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testEventsForUri</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya.rdftriplestore.evaluation/StatementPatternEvalTest/simpleQueryWithBindingSetConstantContext/'><strong>org.apache.rya.rdftriplestore.evaluation.StatementPatternEvalTest.simpleQueryWithBindingSetConstantContext</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya.rdftriplestore.evaluation/StatementPatternEvalTest/simpleQueryNoBindingSetConstantContext/'><strong>org.apache.rya.rdftriplestore.evaluation.StatementPatternEvalTest.simpleQueryNoBindingSetConstantContext</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya.rdftriplestore.evaluation/StatementPatternEvalTest/simpleQueryWithBindingSetSameContext/'><strong>org.apache.rya.rdftriplestore.evaluation.StatementPatternEvalTest.simpleQueryWithBindingSetSameContext</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/536/org.apache.rya$rya.sail/testReport/org.apache.rya.rdftriplestore.evaluation/StatementPatternEvalTest/simpleQueryWithoutBindingSets/'><strong>org.apache.rya.rdftriplestore.evaluation.StatementPatternEvalTest.simpleQueryWithoutBindingSets</strong></a></li></ul>

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/<h2>Failed Tests: <span class='status-failure'>13</span></h2><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.indexing' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.indexing/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.indexing</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.indexing/testReport/org.apache.rya.indexing.statement.metadata/AccumuloStatementMetadataNodeTest/simpleQueryWithVariableContextAndJoinOnContext/'><strong>org.apache.rya.indexing.statement.metadata.AccumuloStatementMetadataNodeTest.simpleQueryWithVariableContextAndJoinOnContext</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.indexing/testReport/org.apache.rya.indexing.statement.metadata/AccumuloStatementMetadataNodeTest/simpleQueryWithConstantContext/'><strong>org.apache.rya.indexing.statement.metadata.AccumuloStatementMetadataNodeTest.simpleQueryWithConstantContext</strong></a></li></ul><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.sail' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.sail/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.sail</a>: <span class='status-failure'>11</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testSimpleMergeJoinMultiWay/'><strong>org.apache.rya.MergeJoinTest.testSimpleMergeJoinMultiWay</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testMergeJoinMultiWay/'><strong>org.apache.rya.MergeJoinTest.testMergeJoinMultiWay</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testSimpleMergeJoin/'><strong>org.apache.rya.MergeJoinTest.testSimpleMergeJoin</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreConnectionTest/testNamedGraphLoad/'><strong>org.apache.rya.RdfCloudTripleStoreConnectionTest.testNamedGraphLoad</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreConnectionTest/testSPOObjRange/'><strong>org.apache.rya.RdfCloudTripleStoreConnectionTest.testSPOObjRange</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testHeartbeatCounts/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testHeartbeatCounts</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testEventsBtwnSystems/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testEventsBtwnSystems</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testAllEvents/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testAllEvents</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testEventsForUri/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testEventsForUri</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.sail/testReport/org.apache.rya.rdftriplestore.evaluation/StatementPatternEvalTest/simpleQueryWithBindingSetConstantContext/'><strong>org.apache.rya.rdftriplestore.evaluation.StatementPatternEvalTest.simpleQueryWithBindingSetConstantContext</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/541/org.apache.rya$rya.sail/testReport/org.apache.rya.rdftriplestore.evaluation/StatementPatternEvalTest/simpleQueryWithBindingSetWithContext/'><strong>org.apache.rya.rdftriplestore.evaluation.StatementPatternEvalTest.simpleQueryWithBindingSetWithContext</strong></a></li></ul>

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/543/<h2>Failed Tests: <span class='status-failure'>8</span></h2><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.sail' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/543/org.apache.rya$rya.sail/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.sail</a>: <span class='status-failure'>8</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/543/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testSimpleMergeJoinMultiWay/'><strong>org.apache.rya.MergeJoinTest.testSimpleMergeJoinMultiWay</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/543/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testMergeJoinMultiWay/'><strong>org.apache.rya.MergeJoinTest.testMergeJoinMultiWay</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/543/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testSimpleMergeJoin/'><strong>org.apache.rya.MergeJoinTest.testSimpleMergeJoin</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/543/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreConnectionTest/testSPOObjRange/'><strong>org.apache.rya.RdfCloudTripleStoreConnectionTest.testSPOObjRange</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/543/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testHeartbeatCounts/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testHeartbeatCounts</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/543/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testEventsBtwnSystems/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testEventsBtwnSystems</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/543/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testAllEvents/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testAllEvents</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/543/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testEventsForUri/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testEventsForUri</strong></a></li></ul>

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/544/<h2>Failed Tests: <span class='status-failure'>3</span></h2><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.sail' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/544/org.apache.rya$rya.sail/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.sail</a>: <span class='status-failure'>3</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/544/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testSimpleMergeJoinMultiWay/'><strong>org.apache.rya.MergeJoinTest.testSimpleMergeJoinMultiWay</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/544/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testMergeJoinMultiWay/'><strong>org.apache.rya.MergeJoinTest.testMergeJoinMultiWay</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/544/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testSimpleMergeJoin/'><strong>org.apache.rya.MergeJoinTest.testSimpleMergeJoin</strong></a></li></ul>

**Comment by DLotts** [comment]
I am able to reproduce the three tests failures above.  It hopefully has to do with the tests.  We can no longer expect a string object in the query to match a URI object in the data, and the reverse.  

Strings are formed by new RyaType(String) and URI objects are formed by new RyaURI(String).
I am going to work on other things and hopefully come back to this.  Feel free to tackle it yourself.

**Pull request closed without merging**
