### PR TITLE
Added giraph profile to resolve an incompatible license issue.

### PR DESCRIPTION
**Pull request by jdasch**
## Description
Added a profile to make rya.giraph an optional module in the maven build.

### Tests
N/A

### Checklist
- [ ] Code Review
- [ ] Squash Commits

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/690/

**Comment by joshelser** [comment]
Hrm, maybe worth it to send a note to the Giraph mailing lists? If this really is an LGPL dependency, then Apache Giraph shouldn't be depending on it either.

**Comment by jdasch** [comment]
Good idea.  I just pinged their dev list.

**Comment by adinancr** [comment]
I'll merge this so we can release Rya. When/if Giraph fixes their code to remove the LGPL dependency, we can remove the optional part of the Rya- Giraph module

**Pull request closed without merging**
