### PR TITLE
RYA-268 Adding Geoindexing Profile to Web project

### PR DESCRIPTION
**Pull request by amihalik**
## Description
Added a geoindexing profile to the web project

### Tests
no new tests

### Links
[Jira RYA-286](https://issues.apache.org/jira/browse/RYA-286)

### Checklist
- [ ] Code Review
- [ ] Squash Commits

#### People To Review
@meiercaleb @isper3at

### CODE REVIEW

**Comment by amihalik** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/219/

**Comment by amihalik** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/222/<h2>Build result: FAILURE</span></h2>[...truncated 6.38 MB...][INFO] Apache Rya Spark Support ........................... SUCCESS [ 22.111 s][INFO] Apache Rya Web Projects ............................ SUCCESS [  5.522 s][INFO] Apache Rya Web Implementation ...................... FAILURE [ 16.564 s][INFO] ------------------------------------------------------------------------[INFO] BUILD FAILURE[INFO] ------------------------------------------------------------------------[INFO] Total time: 41:41 min[INFO] Finished at: 2017-06-02T23:19:25+00:00[INFO] Final Memory: 233M/1082M[INFO] ------------------------------------------------------------------------Waiting for Jenkins to finish collecting data[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (default) on project web.rya: Error resolving project artifact: Could not transfer artifact org.geotools:gt-graph:pom:14.3 from/to geowave-maven-releases (https://s3.amazonaws.com/geowave-maven/release): Access denied to: https://s3.amazonaws.com/geowave-maven/release/org/geotools/gt-graph/14.3/gt-graph-14.3.pom, ReasonPhrase: Forbidden. for project org.geotools:gt-graph:jar:14.3 -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException[ERROR] [ERROR] After correcting the problems, you can resume the build with the command[ERROR]   mvn <goals> -rf :web.ryachannel stoppedSetting status of 6a3923c73da658006ea57c0e83b1ea48f114bbfd to FAILURE with url https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/222/ and message: 'Build finished. 'Using context: Jenkins: clean package -Pgeoindexing

**Comment by amihalik** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/232/<h2>Build result: FAILURE</span></h2>[...truncated 7.66 MB...][INFO] Apache Rya Web Projects ............................ SUCCESS [  2.388 s][INFO] Apache Rya Web Implementation ...................... FAILURE [  5.474 s][INFO] ------------------------------------------------------------------------[INFO] BUILD FAILURE[INFO] ------------------------------------------------------------------------[INFO] Total time: 43:05 min[INFO] Finished at: 2017-06-12T21:19:53+00:00[INFO] Final Memory: 234M/1326M[INFO] ------------------------------------------------------------------------Waiting for Jenkins to finish collecting data[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (default) on project web.rya: Error resolving project artifact: Could not transfer artifact org.geotools:gt-graph:pom:14.3 from/to geowave-maven-releases (https://s3.amazonaws.com/geowave-maven/release): Access denied to: https://s3.amazonaws.com/geowave-maven/release/org/geotools/gt-graph/14.3/gt-graph-14.3.pom, ReasonPhrase: Forbidden. for project org.geotools:gt-graph:jar:14.3 -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException[ERROR] [ERROR] After correcting the problems, you can resume the build with the command[ERROR]   mvn <goals> -rf :web.ryachannel stoppedSetting status of 6a3923c73da658006ea57c0e83b1ea48f114bbfd to FAILURE with url https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/232/ and message: 'Build finished. 'Using context: Jenkins: clean package -Pgeoindexing

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/254/<h2>Build result: ABORTED</span></h2>[...truncated 6.69 MB...] T E S T S-------------------------------------------------------Running org.apache.rya.export.accumulo.parent.AccumuloParentMetadataRepositoryAdapterTestTests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.189 sec - in org.apache.rya.export.accumulo.parent.AccumuloParentMetadataRepositoryAdapterTestRunning org.apache.rya.export.accumulo.AccumuloRyaStatementStoreTest#:apple     1499810978573#:apple     1499810978574Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.345 sec - in org.apache.rya.export.accumulo.AccumuloRyaStatementStoreTestRunning org.apache.rya.export.api.conf.AccumuloConfigurationAdapterTestTests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.038 sec - in org.apache.rya.export.api.conf.AccumuloConfigurationAdapterTestResults :Tests run: 14, Failures: 0, Errors: 0, Skipped: 0[WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 40 iota=55[INFO] [INFO] --- animal-sniffer-maven-plugin:1.15:check (default) @ rya.export.accumulo ---[INFO] Checking unresolved references to org.codehaus.mojo.signature:java18:1.0Build was abortedchannel stoppedSetting status of 148b1cd1a1177d69ceb3ecbc63f698dac6cdfdd5 to FAILURE with url https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/254/ and message: 'FAILURE 'Using context: Jenkins: clean package -Pgeoindexing

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/255/<h2>Build result: ABORTED</span></h2>[...truncated 6.60 MB...][INFO] Changes detected - recompiling the module![INFO] Compiling 3 source files to /home/jenkins/jenkins-slave/workspace/incubator-rya-master-with-optionals-pull-requests/extras/rya.pcj.fluo/pcj.fluo.demo/target/classes[WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 12 iota=55[INFO] [INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ rya.pcj.fluo.demo ---[INFO] Using 'UTF-8' encoding to copy filtered resources.[INFO] skip non existing resourceDirectory /home/jenkins/jenkins-slave/workspace/incubator-rya-master-with-optionals-pull-requests/extras/rya.pcj.fluo/pcj.fluo.demo/src/test/resources[INFO] Copying 3 resources[WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 12 iota=55[INFO] [INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ rya.pcj.fluo.demo ---[INFO] No sources to compile[WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 12 iota=55[INFO] [INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ rya.pcj.fluo.demo ---[WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 12 iota=55[INFO] [INFO] --- animal-sniffer-maven-plugin:1.15:check (default) @ rya.pcj.fluo.demo ---[INFO] Checking unresolved references to org.codehaus.mojo.signature:java18:1.0Build was abortedchannel stoppedSetting status of 284ffd4558603681a2491d74794b2ef5a27edb95 to FAILURE with url https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/255/ and message: 'FAILURE 'Using context: Jenkins: clean package -Pgeoindexing

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/256/

**Pull request closed without merging**
