### PR TITLE
RYA-413 Fixed how MongoDBRyaDAO closed its internal mongoClient.  Updated AbstractMongoDBRdfConfigurationBuilder config tags.

### PR DESCRIPTION
**Pull request by ejwhite922**
## Description
If the MongoDBRyaDAO is destroyed, its internal mongoClient is not disposed correctly.  This leaves the mongoClient closed which causes problems the next time the MongoDBRyaDAO is created.

The mongoClient is managed by MongoConnectorFactory and needs to be null'ed out to be recreated properly (by calling MongoConnectorFactory.closeMongoClient(); instead of mongoClient.close();)

Some new unit tests were added to test reconstructing the DAO.  They failed with the old way of using mongoClient.close() and pass with the new way of using MongoConnectorFactory.closeMongoClient().

Also, all the static final config tags inside AbstractMongoDBRdfConfigurationBuilder were changed from protected to public (like AbstractAccumuloRdfConfigurationBuilder has) so they could be used inside other tests that make use of the tags.

### Tests
Unit tests

### Links
[Jira](https://issues.apache.org/jira/browse/RYA-413)

### Checklist
- [ ] Code Review
- [ ] Squash Commits

#### People To Review
@meiercaleb 
@kchilton2 
@jessehatfield 
@isper3at 
@DLotts
@pujav65

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/566/

**Comment by ejwhite922** [comment]
Rebased this review off RYA-303.  Only the latest commit should be review "RYA-413 Fixed how MongoDBRyaDAO..."

The main change is removing mongoClient.close() from MongoDBRyaDAO.destroy().  This may or may not be desirable.  Should the mongoClient be closed from StatefulMongoDBRdfConfiguration when the JVM shuts down?  I only see EmbeddedMongoSingleton closing the mongoClient but it appears that's only used for testing.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/598/<h2>Build result: FAILURE</span></h2>[...truncated 705.55 KB...][INFO] Final Memory: 159M/3066M[INFO] ------------------------------------------------------------------------[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:testCompile (default-testCompile) on project rya.indexing: Compilation failure: Compilation failure:[ERROR] /home/jenkins/jenkins-slave/workspace/incubator-rya-master-with-optionals-pull-requests/extras/indexing/src/test/java/org/apache/rya/api/client/accumulo/AccumuloInstallIT.java:[95,17] method install_withIndexers() is already defined in class org.apache.rya.api.client.accumulo.AccumuloInstallIT[ERROR] /home/jenkins/jenkins-slave/workspace/incubator-rya-master-with-optionals-pull-requests/extras/indexing/src/test/java/org/apache/rya/api/client/accumulo/AccumuloInstallIT.java:[114,15] cannot find symbol[ERROR] symbol:   class Install[ERROR] location: class org.apache.rya.api.client.accumulo.AccumuloInstallIT[ERROR] /home/jenkins/jenkins-slave/workspace/incubator-rya-master-with-optionals-pull-requests/extras/indexing/src/test/java/org/apache/rya/api/client/accumulo/AccumuloInstallIT.java:[118,15] cannot find symbol[ERROR] symbol:   class InstanceExists[ERROR] location: class org.apache.rya.api.client.accumulo.AccumuloInstallIT[ERROR] -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException[ERROR] [ERROR] After correcting the problems, you can resume the build with the command[ERROR]   mvn <goals> -rf :rya.indexingchannel stoppedSetting status of a9bd1c0be96e0901e47e56633b827a282c31a302 to FAILURE with url https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/598/ and message: 'FAILURE 'Using context: Jenkins: clean package -Pgeoindexing

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/660/

**Comment by ejwhite922** [comment]
Closing this and reopening in another [PR 263](https://github.com/apache/incubator-rya/pull/263)

**Pull request closed without merging**
