### PR TITLE
RYA-110 - Add Uninstall command to Rya Console.

### PR DESCRIPTION
**Pull request by kchilton2**

### CODE REVIEW

**Comment by pujav65** [comment]
hey fix the merge conflict and i will merge.

**Comment by isper3at** [comment]
This PR is now also clean

**Comment by amihalik** [comment]
@isper3at I just noticed your list at [RYA-208](https://issues.apache.org/jira/browse/RYA-208).  I'll comment on that ticket as I merge them.  Thanks again.

**Comment by isper3at** [comment]
Awesome, thanks!

**Pull request closed without merging**
