### PR TITLE
RYA-393 MongoDB Batch Writer Duplicate Key Exception

### PR DESCRIPTION
**Pull request by ejwhite922**
## Description
Fixed MongoDB DAO Batch Writer from dropping statements when batch contains duplicate keys.

### Tests
Integration Tests

### Links
[Jira](https://issues.apache.org/jira/browse/RYA-393)

### Checklist
- [ ] Code Review
- [ ] Squash Commits

#### People To Review
@amihalik 
@meiercaleb 
@pujav65 
@isper3at

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/511/

**Comment by pujav65** [comment]
Looks good.  @isper3at , yes catching the exception prevents the drops because it will keep going rather than crapping out on individual adds -- that was why there was a catch for that exception in the original dao before we introduced the batch writing stuff.

**Comment by amihalik** [comment]
I'm going to hold off on merging this for a minute.  This exception talk has me thinking there are other exceptions that we are not processing correctly. brb

**Comment by amihalik** [comment]
The more I look at this, the more I’m confident that this has to more with the mongo libs and not anything that we wrote for Rya. I’ll try to put together an example tomorrow.

**Comment by amihalik** [comment]
@ejwhite922 There's a couple issues with the batch writer and it doesn't have to do with exceptions being caught.  (1) the QueueFullChecker thread should not be a daemon thread.... "The Java Virtual Machine exits when the only threads running are all daemon threads" means that the JVM will exit while flushing to mongo.  (2) It doesn't seem like the secondary indexer (i.e. geoindexer) is flushed when I close down the sail layer.  Can you double check that?

Also, it seems like the JVM takes a very long time to exit after I call sailrepository.shutDown().  I think has to do with the BatchWriter as well.

**Comment by pujav65** [comment]
wrt to the secondary flushes -- I think there is a jira ticket already for secondary indexers not being flushed appropriately.

**Comment by ejwhite922** [comment]
There is another JIRA ticket for indexers not being flushed: [RYA-72](https://issues.apache.org/jira/browse/RYA-72).  I went ahead and addressed that in this ticket and had the DAOs flush all indexers whenever they flush.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/523/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/530/

**Comment by amihalik** [comment]
Asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/537/

**Pull request closed without merging**
