### PR TITLE
Refactored the rya.periodic.notification.service.

### PR DESCRIPTION
**Pull request by jdasch**
## Description
- Light pom cleaning (removed overrides, renaming, wordsmithing)
- Set maven-failsave-plugin reuseForks=false until RYA-331 is resolved
- Eliminated redundant text in file paths
- This makes adding the twill app for RYA-305 a little cleaner.

### Tests
N/A

### Links
[Jira](https://issues.apache.org/jira/browse/RYA-NUMBER)

### Checklist
- [ ] Code Review
- [ ] Squash Commits

#### People To Reivew
@meiercaleb 
@amihalik 
@isper3at

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/343/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.indexing' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/343/org.apache.rya$rya.indexing/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.indexing</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/343/org.apache.rya$rya.indexing/testReport/org.apache.rya.indexing.mongo/MongoTemporalIndexerTest/org_apache_rya_indexing_mongo_MongoTemporalIndexerTest/'><strong>org.apache.rya.indexing.mongo.MongoTemporalIndexerTest.org.apache.rya.indexing.mongo.MongoTemporalIndexerTest</strong></a></li></ul>

**Comment by jdasch** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/345/

**Comment by jdasch** [comment]
Mostly my OCD.

**Comment by jdasch** [comment]
Punting until RYA-283 gets merged.

**Pull request closed without merging**
