### PR TITLE
RYA-177 adding optional geoindexing profile

### PR DESCRIPTION
**Pull request by pujav65**
Moved geoindexing to a separate project and added a profile.

N/A

### Links
[Jira](https://issues.apache.org/jira/browse/RYA-177)

### Checklist
- [ ] Code Review
- [ x] Squash Commits

#### People To Reivew
@amihalik

### CODE REVIEW

**Comment by pujav65** [comment]
This is meant to be a start to get us through a release -- there are at least three issues that should accompany this:
1.  Bring back the geo examples
2.  Have Map Reduce delegate to the DAO to write to indexers, not writing to them directly
3.  Look at further refactoring to bring back the mongo geoindexing since it doesn't implicitly depend on geotools
I feel these are all relatively minor and could be solved later.

**Comment by amihalik** [comment]
I'm still seeing gt libs pulled into the build eg:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Rya Secondary Indexing 3.2.10-SNAPSHOT
[INFO] ------------------------------------------------------------------------

[...]

[INFO] Including org.geotools.xsd:gt-xsd-core:jar:14.3 in the shaded jar.
[INFO] Including org.geotools:gt-graph:jar:14.3 in the shaded jar.
```

What's the plan to resolve these before a release?

**Comment by pujav65** [comment]
Sorry missed the jt dependency that was pulling those in.  Let me know if you see anything else being pulled in.

**Comment by amihalik** [comment]
Better.  I'm still seeing gt dependencies.

try running `mvn dependency:tree | grep gt` in your environment.  I get this:

```
[INFO] |  |  |  +- org.geotools:gt-referencing:jar:14.1:compile
[INFO] |  |  |  +- org.geotools:gt-grid:jar:14.1:compile
[INFO] |  |  |  \- org.geotools:gt-transform:jar:14.1:compile
[INFO] |  |  +- org.geotools:gt-main:jar:14.1:compile
[INFO] |  |  +- org.geotools:gt-api:jar:14.1:compile
[INFO] |  |  +- org.geotools:gt-data:jar:14.1:compile
[INFO] |  |  +- org.geotools:gt-cql:jar:14.1:compile
[INFO] |  |  +- org.geotools:gt-metadata:jar:14.1:compile
[INFO] |  |  +- org.geotools:gt-render:jar:14.1:compile
[INFO] |  |  |  \- org.geotools:gt-coverage:jar:14.1:compile
[INFO] |  |  +- org.geotools:gt-process-feature:jar:14.1:compile
[INFO] |  |  |  \- org.geotools:gt-process:jar:14.1:compile
[INFO] |  |  |     \- org.geotools:gt-shapefile:jar:14.1:compile
[INFO] |  +- org.geotools:gt-opengis:jar:14.1:compile
```

**Comment by pujav65** [comment]
hey aaron i can't recreate this.  Can you verify that you are running with the geoindexing profile not enabled and that you have my last commit?  I ran mvn dependency:tree, piped to file, and then searched for gt.  Didn't bring this up.

**Comment by amihalik** [comment]
Yep, I will missing a commit.  Looks good.  Building and running the tests now.

**Comment by joshelser** [comment]
Looks reasonable enough. I'll try to pull down the changes and take a look tmrw with fresh eyes.

**Pull request closed without merging**
