### PR TITLE
RYA-315 Fixing issue with Core Indices on MongoDB

### PR DESCRIPTION
**Pull request by amihalik**
## Description
Fixed issue with building OS index. This was causing the very slow query response on the ?s ?p <o> queries

### Links
[Jira](https://issues.apache.org/jira/browse/RYA-315)

### Checklist
- [ ] Code Review
- [ ] Squash Commits

#### People To Review
@isper3at 
@meiercaleb

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/265/<h2>Build result: FAILURE</span></h2>[...truncated 8.93 MB...][INFO] Apache Rya Spark Support ........................... SKIPPED[INFO] Apache Rya Web Projects ............................ SKIPPED[INFO] Apache Rya Web Implementation ...................... SKIPPED[INFO] ------------------------------------------------------------------------[INFO] BUILD FAILURE[INFO] ------------------------------------------------------------------------[INFO] Total time: 54:22 min[INFO] Finished at: 2017-07-18T20:53:03+00:00[INFO] Final Memory: 194M/1108M[INFO] ------------------------------------------------------------------------[ERROR] Failed to execute goal on project rya.geoindexing: Could not resolve dependencies for project org.apache.rya:rya.geoindexing:jar:3.2.11-incubating-SNAPSHOT: Failed to collect dependencies at org.locationtech.geomesa:geomesa-accumulo-datastore_2.11:jar:1.3.0-m1 -> org.locationtech.geomesa:geomesa-feature-all_2.11:jar:1.3.0-m1 -> org.locationtech.geomesa:geomesa-feature-kryo_2.11:jar:1.3.0-m1 -> org.geotools:gt-process-feature:jar:15.1 -> org.geotools:gt-process:jar:15.1 -> org.geotools:gt-coverage:jar:15.1 -> it.geosolutions.imageio-ext:imageio-ext-tiff:jar:1.1.15: Failed to read artifact descriptor for it.geosolutions.imageio-ext:imageio-ext-tiff:jar:1.1.15: Could not transfer artifact it.geosolutions.imageio-ext:imageio-ext-tiff:pom:1.1.15 from/to geowave-maven-releases (https://s3.amazonaws.com/geowave-maven/release): Access denied to: https://s3.amazonaws.com/geowave-maven/release/it/geosolutions/imageio-ext/imageio-ext-tiff/1.1.15/imageio-ext-tiff-1.1.15.pom , ReasonPhrase:Forbidden. -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException[ERROR] [ERROR] After correcting the problems, you can resume the build with the command[ERROR]   mvn <goals> -rf :rya.geoindexingchannel stoppedSetting status of 7778a4685ae70f67f9b0354fcbec7d30f0beaf7a to FAILURE with url https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/265/ and message: 'FAILURE 'Using context: Jenkins: clean package -Pgeoindexing

**Comment by amihalik** [comment]
This is a very strange error... it can't download a dependency... but I can... :/

Here's the dependency:

[INFO] Downloading: https://repo.boundlessgeo.com/main/it/geosolutions/imageio-ext/imageio-ext-tiff/1.1.15/imageio-ext-tiff-1.1.15.pom

I'm going to see what happens when I build again.

**Comment by amihalik** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/266/

**Pull request closed without merging**
