### PR TITLE
RYA-350 Added EmbeddedKafkaSingleton to help eliminate flaky ITs.

### PR DESCRIPTION
**Pull request by jdasch**
## Description
Added EmbeddedKafkaSingleton, EmbeddedKafkaInstance, and KafkaTestInstanceRule.  Updated KafkaITBase and PeriodicNotificationExporterIT to take advantage of these new classes.

Flakyness of the IT appeared to arise from kafka topics not existing before a race condition between the publishers and subscribers.  Creating them before the test solves this issue.  The new classes represent a subset of the fixes being provided in RYA-331.  They are being added now to avoid redundant effort.

### Tests
PeriodicNotificationExporterIT, KafkaITBase

### Links
[Jira RYA-350](https://issues.apache.org/jira/browse/RYA-350)

### Checklist
- [ ] Code Review
- [x] Squash Commits

#### People To Reivew
@meiercaleb 
@amihalik 
@isper3at

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/428/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/429/

**Comment by pujav65** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/435/

**Comment by jdasch** [comment]
As best as I can tell, I've resolved the flakiness with the PeriodicNotificationExporterIT.  I think that it is ready to merge.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/453/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/457/

**Pull request closed without merging**
