### PR TITLE
Input format fix

### PR DESCRIPTION
**Pull request by jej2003**
fix to pull in timestamp, column visibility and value

### CODE REVIEW

**Comment by pujav65** [comment]
This pr causes a test to fail -- RyaInputFormatTest seems to fail.  Can you fix the test and then I will merge it.

**Comment by amihalik** [comment]
Puja: I updated the committer instructions on the [confluence](https://cwiki.apache.org/confluence/display/RYA/Contributing+to+Rya) page.  I used this PR as the specific example.  Can you try them out?

**Comment by jej2003** [comment]
@pujav65 I updated the test that I had missed previously, but after trying to rebase this branch on develop there are fluo tests that do not pass.  I believe these are not related to my additions and to verify checked out develop and I am getting a ton of zookeeper connection errors.

**Comment by amihalik** [comment]
@jej2003 the exceptions are expected.  These tests work fine on my box, so I'm fine if @pujav65 merges it.

**Comment by pujav65** [comment]
Yes, that's an issue with running mini-accumulo on Windows.  As long as the input format test passes, I can take it from here.

**Comment by jej2003** [comment]
@amihalik The exceptions I get are zookeeper connection exceptions and the tests never complete.  I am used to the expected exceptions that get printed but this causes an endless stream of connection errors like

`2016-04-07 14:02:15,283 INFO  [main-SendThread(localhost:64658)] zookeeper.ClientCnxn (ClientCnxn.java:logStartConnect(975)) - Opening socket connection to server localhost/127.0.0.1:64658. Will not attempt to authenticate using SASL (unknown error)
2016-04-07 14:02:15,284 WARN  [main-SendThread(localhost:64658)] zookeeper.ClientCnxn (ClientCnxn.java:run(1102)) - Session 0x153f1e34c110005 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)`

The last test that is mentioned is 

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.rya.indexing.pcj.fluo.api.CountStatementsIT
2016-04-07 14:01:49,201 INFO  [main] impl.MiniAccumuloClusterImpl (MiniAccumuloClusterImpl.java:start(573)) - Starting MAC against instance miniInstance and zookeeper(s) localhost:22807.
2016-04-07 14:01:52,190 WARN  [main] client.ClientConfiguration (ClientConfiguration.java:loadFromSearchPath(155)) - Found no client.conf in default paths. Using default client configuration values.
2016-04-07 14:01:52,258 INFO  [main] zookeeper.ZooKeeper (Environment.java:logEnv(100)) - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT

Perhaps a zookeeper client isn't being shutdown and it is stuck in a loop trying to reconnect?  I'm doing the following to test the develop branch without this merged

mvn clean verify

**Comment by DLotts** [comment]
I've seen this error.  I believe that the Mock Accumulo is shutting down before the tests complete.  Then "zookeeper.ClientCnxn" fails to connect to zookeeper because it is gone.

**Comment by pujav65** [comment]
merged.  can you please close the pull request?

**Pull request closed without merging**
