### PR TITLE
RYA-488 Moved the Geo Indexing specific maven repositories into the g…

### PR DESCRIPTION
**Pull request by kchilton2**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/731/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.streams.query-manager' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/731/org.apache.rya$rya.streams.query-manager/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.streams.query-manager</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/731/org.apache.rya$rya.streams.query-manager/testReport/org.apache.rya.streams.querymanager/LogEventWorkerTest/nofity_logCreated_doesNotExist/'><strong>org.apache.rya.streams.querymanager.LogEventWorkerTest.nofity_logCreated_doesNotExist</strong></a></li></ul>

**Comment by kchilton2** [comment]
That test failing has nothing to do with this commit. We should open a defect and fix the test.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/741/

**Comment by kchilton2** [comment]
Could somebody code review this or pull it in?

**Comment by pujav65** [comment]
ok i will pull in

**Pull request closed without merging**
