### PR TITLE
RYA-397 Renamed MockMongoSingleton/Factory to Embedded

### PR DESCRIPTION
**Pull request by isper3at**
Since they create/use Embedded Mongo, not Mock
renamed to show what they actually use.

File renames

N/A

### Links
[Jira](https://issues.apache.org/jira/browse/RYA-397)

### Checklist
- [ ] Code Review
- [x] Squash Commits

#### People To Reivew
@meiercaleb 
@jdasch

### CODE REVIEW

**Comment by jdasch** [comment]
Yay!  I think you missed a couple classes though.  `MongoITBase` and `MongoIndexerDeleteIT` have references.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/514/<h2>Build result: FAILURE</span></h2>[...truncated 1.61 MB...][ERROR] location: class InferenceExamples[ERROR] /home/jenkins/jenkins-slave/workspace/incubator-rya-master-with-optionals-pull-requests/extras/indexingExample/src/main/java/InferenceExamples.java:[157,43] cannot find symbol[ERROR] symbol:   variable MockMongoFactory[ERROR] location: class InferenceExamples[ERROR] /home/jenkins/jenkins-slave/workspace/incubator-rya-master-with-optionals-pull-requests/extras/indexingExample/src/main/java/MongoRyaDirectExample.java:[94,26] cannot find symbol[ERROR] symbol:   class MockMongoFactory[ERROR] location: class MongoRyaDirectExample[ERROR] /home/jenkins/jenkins-slave/workspace/incubator-rya-master-with-optionals-pull-requests/extras/indexingExample/src/main/java/MongoRyaDirectExample.java:[300,35] cannot find symbol[ERROR] symbol:   variable MockMongoFactory[ERROR] location: class MongoRyaDirectExample[ERROR] -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException[ERROR] [ERROR] After correcting the problems, you can resume the build with the command[ERROR]   mvn <goals> -rf :rya.indexing.examplechannel stoppedSetting status of b429bae0f3d4568ffd0e9deb6c4b44efc6072530 to FAILURE with url https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/514/ and message: 'FAILURE 'Using context: Jenkins: clean package -Pgeoindexing

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/515/

**Comment by jdasch** [comment]
Oh, and this builds for me.  yay.

**Pull request closed without merging**
