### PR TITLE
RYA-135 Hard code triples collection

### PR DESCRIPTION
**Pull request by isper3at**
There is no need for the triples collection to be configurable, as
only the mongo database name will change the rya instance.

N/A

### Links
[Jira](https://issues.apache.org/jira/browse/RYA-NUMBER)

### Checklist
- [ ] Code Review
- [x] Squash Commits

#### People To Reivew
@pujav65 
@kchilton2 
@ejwhite922

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/769/<h2>Failed Tests: <span class='status-failure'>4</span></h2><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:mongodb.rya' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/769/org.apache.rya$mongodb.rya/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:mongodb.rya</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/769/org.apache.rya$mongodb.rya/testReport/org.apache.rya.mongodb/MongoDBRdfConfigurationTest/testBuilder/'><strong>org.apache.rya.mongodb.MongoDBRdfConfigurationTest.testBuilder</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/769/org.apache.rya$mongodb.rya/testReport/org.apache.rya.mongodb/MongoDBRdfConfigurationTest/testBuilderFromProperties/'><strong>org.apache.rya.mongodb.MongoDBRdfConfigurationTest.testBuilderFromProperties</strong></a></li></ul><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.indexing' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/769/org.apache.rya$rya.indexing/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.indexing</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/769/org.apache.rya$rya.indexing/testReport/org.apache.rya.indexing.mongo/MongoIndexingConfigurationTest/testBuilder/'><strong>org.apache.rya.indexing.mongo.MongoIndexingConfigurationTest.testBuilder</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/769/org.apache.rya$rya.indexing/testReport/org.apache.rya.indexing.mongo/MongoIndexingConfigurationTest/testBuilderFromProperties/'><strong>org.apache.rya.indexing.mongo.MongoIndexingConfigurationTest.testBuilderFromProperties</strong></a></li></ul>

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/772/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/774/

**Comment by isper3at** [comment]
opening a new PR against RYA master after 3.x  https://github.com/apache/incubator-rya/pull/300 is in

**Pull request closed without merging**
