### PR TITLE
RYA-17, RYA-19, RYA-20, RYA-10 issue with mongo deletes, typo in constructor,…

### PR DESCRIPTION
**Pull request by pujav65**
… redundant indices

### CODE REVIEW

**Comment by amihalik** [comment]
Looks good.  I'll pull it in.

**Comment by amihalik** [comment]
You added a new file (`MongoDBRyaDAOTest.java`) and it doesn't have a license header (so it failed `mvn apache-rat:check`).  Please go back in and add the header, then I'll pull in this PR.

**Comment by pujav65** [comment]
fixed the license on the new test, and then implemented something for RYA-10 (reusing existing collections for geo queries).  Someone should implement more of the geo functionality, that can be a follow on task though.

**Comment by amihalik** [comment]
Does this PR close all of these issues? RYA-17, RYA-19, RYA-20, RYA-10?

**Comment by pujav65** [comment]
Yup.  I missed what was happening with jira today -- everything in a good state?  Want me to look at it at all?

**Comment by amihalik** [comment]
merged into develop

**Comment by pujav65** [comment]
merged

**Pull request closed without merging**
