### PR TITLE
[WIP] RYA-94 Remove from secondary indexes when deleting from DAO

### PR DESCRIPTION
**Pull request by DLotts**
Not ready for review yet.  More commits to come.

### CODE REVIEW

**Comment by pujav65** [comment]
hey david,
Two things:
1.  Merge to develop not master
2.  Mark the Pull request as WIP if its not ready to be merged

**Comment by amihalik** [comment]
Please change this to point to the apache master branch.

**Comment by pujav65** [comment]
hey david, is this still in progress or was it made obsolete by another pull request?

**Comment by DLotts** [comment]
It was blocked by another Mongo issue, but that was fixed and so this should be complete-able now. 
BTW: It's only an issue with Mongo.

This method: /mongodb.rya/src/main/java/mvm/rya/mongodb/MongoDBRyaDAO.delete() 
needs a loop like this:
for (RyaSecondaryIndexer index : secondaryIndexers)
{ index.delete(ryaStatement); } 
david.

**Comment by DLotts** [comment]
Already addressed elsewhere, closing!

**Pull request closed without merging**
