### PR TITLE
RYA-269 Remove references to mvm

### PR DESCRIPTION
**Pull request by wollefitz**
Replaced all references to old identifier mvm.rya by org.apache.rya

none

### Links
[Jira](https://issues.apache.org/jira/browse/RYA-269)

### Checklist
- [ ] Code Review
- [ ] Squash Commits

#### People To Reivew
[Add those who should review this]

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by pujav65** [comment]
Looks good to me!  Thanks for the contribution.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by wollefitz** [comment]
Pressed the wrong button - patch doesn't have to be verified. But https://issues.apache.org/jira/browse/RYA-269 can be closed, too, then.

**Pull request closed without merging**
