### PR TITLE
RYA-443 Fixed Rya Streams Query Manager RPM version

### PR DESCRIPTION
**Pull request by ejwhite922**
## Description
Fixed the Query Manager RPM so that the "rpm.version" property gets generated and replaced in all the scripts.

### Tests
Build

### Links
[Jira](https://issues.apache.org/jira/browse/RYA-443)

### Checklist
- [ ] Code Review
- [ ] Squash Commits

#### People To Review
@isper3at 
@DLotts
@pujav65

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/705/

**Comment by ejwhite922** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/708/

**Comment by kchilton2** [comment]
This patch does not create an RPM that can be uninstalled. I'm going to revert all of these changes that Eric made to how we build RPMs out, and put my stuff back in. I'll make the RPM build a profile so Windows users can still build our app.

**Comment by kchilton2** [comment]
https://github.com/apache/incubator-rya/pull/284

**Comment by ejwhite922** [comment]
I just tested today and this patch works on my CentOS 7 VM.  I did an install -> uninstall -> install -> uninstall of the rpm which all completed successfully.  I used the following:

```
sudo yum install -y rya.streams.query-manager-3.2.13-incubating-0.201803161404-noarch.rpm
sudo yum remove rya.streams.query-manager.noarch
```

I suspect uninstall issues came from using the rpm from master and then trying to use this patch on a VM that had its rya.streams.query-manager rpm version in a bad state.

I would recommend this patch over [#284](https://github.com/apache/incubator-rya/pull/284) since it will allow Jenkins to build and distribute the rpm, doesn't require an undocumented profile flag, and is build-able on all platforms.

**Comment by jdasch** [comment]
Interesting that you included the architecture type as part of the package name.  Can you confirm the following command also works?   
```
sudo yum install -y rya.streams.query-manager-3.2.13-incubating-0.201803161404-noarch.rpm
sudo yum remove rya.streams.query-manager
```

Sigh, I'm looking forward to the day this package is called `rya-streams-query-manager`.

**Comment by ejwhite922** [comment]
@jdasch Yep, `sudo yum remove rya.streams.query-manager` works as well.

**Comment by kchilton2** [comment]
I used the RPM you gave me built using this patch when it did not work. I had never installed the bad state RPM.

**Comment by kchilton2** [comment]
Also, to uninstall it I was using
rpm -qa | grep rya

Then whatever that reported as the installed package I used 
rpm -e <that here>

That is what is not working.

**Comment by ejwhite922** [comment]
What error is it giving?

I am able to run `sudo rpm -e rya.streams.query-manager` without issue.

I'll upload the rpm that is working for me to my share.  Sorry I was in a rush yesterday so I only built the query-manager project and it looks like it didn't include everything (judging from the size difference).  The rpm from today comes from a full build.

**Comment by isper3at** [comment]
rpm -e does not work when you supply a version number.  Not sure if I trust that >..>

**Comment by ejwhite922** [comment]
I fixed the issue with `rpm -e` not working with the version number.  The plugin's version property was including "-incubating" which RPM's don't like "-" in that property.  The version and release properties are appropriate now; taken from what the rpm-maven-plugin produces.

The new commit generates an RPM file with a name like:
`rya.streams.query-manager-3.2.13-incubating_SNAPSHOT20180404214440-noarch.rpm`
With `3.2.13` being assigned to the version property and `incubating_SNAPSHOT20180404214440` to the release property.

Using `rpm -qa | grep rya` returns:
`rya.streams.query-manager-3.2.13-incubating_SNAPSHOT20180404214440.noarch`

I confirmed that all the following work for uninstall:
```
sudo yum remove rya.streams.query-manager-3.2.13-incubating_SNAPSHOT20180404214440.noarch
sudo yum remove rya.streams.query-manager-3.2.13-incubating_SNAPSHOT20180404214440
sudo yum remove rya.streams.query-manager-3.2.13
sudo yum remove rya.streams.query-manager
sudo rpm -e rya.streams.query-manager-3.2.13-incubating_SNAPSHOT20180404214440.noarch
sudo rpm -e rya.streams.query-manager-3.2.13-incubating_SNAPSHOT20180404214440
sudo rpm -e rya.streams.query-manager-3.2.13
sudo rpm -e rya.streams.query-manager
```

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/722/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/723/

**Comment by pujav65** [comment]
@ejwhite922 my understanding is that @kchilton2 pr makes this one obe.  So I will close it when I pull in that one.

**Comment by ejwhite922** [comment]
That one can't be built by Jenkins so the rpm would need to be built locally.

**Comment by kchilton2** [comment]
This can be declined.

**Comment by kchilton2** [comment]
Eric, please close this.

**Pull request closed without merging**
