### PR TITLE
RYA-332 rename integration tests

### PR DESCRIPTION
**Pull request by isper3at**
Some integration tests were being ignored
since the class names ended with
"IntegrationTest" instead of "IT"

N/A

### Links
[Jira](https://issues.apache.org/jira/browse/RYA-332)

### Checklist
- [ ] Code Review
- [x] Squash Commits

#### People To Reivew
@jdasch
@meiercaleb

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/422/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/427/

**Comment by meiercaleb** [comment]
I'm fine with this PR as soon as you fix the broken Camel integration tests.

**Comment by jdasch** [comment]
Ditto. Looks good.  Just need to fix this test: org.apache.rya.camel.cbsail.CbSailIT.testCbSail

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/452/

**Pull request closed without merging**
