### PR TITLE
Fixed tests that are sensitive to DST spring forward.

### PR DESCRIPTION
**Pull request by DLotts**
## Description
Fixed failed assertion here:
org.apache.rya.api.functions.DateTimeWithinPeriodTest.testWeeks(DateTimeWithinPeriodTest.java:145)
Failed because of DST transition.  Test is using the current date and time.  Changed to fixed datetime.

### Tests
No new tests.

### Links
[Jira RYA-476](https://issues.apache.org/jira/browse/RYA-476)

### Checklist
- [ ] Code Review
- [ ] Squash Commits

#### People To Review
anyone

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/706/

**Comment by DLotts** [comment]
asfbot build

**Comment by DLotts** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/707/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/710/

**Comment by DLotts** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/711/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/712/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/713/

**Pull request merged**
