### PR TITLE
RYA-489 Moved common Accumulo integration test code to the rya.test.accumulo project.

### PR DESCRIPTION
**Pull request by kchilton2**
This is pretty much just a repackaging commit. I moved the generic accumulo test code to a new "rya.test.accumulo" project. I had to introduce some code for performing installation steps to one of the test classes.

Only review 489. It depends on the 4.0.0 branch, so I had to include more commits.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/739/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/740/

**Comment by kchilton2** [comment]
Could somebody code review this or pull it in?

**Comment by pujav65** [comment]
pulling this in

**Pull request closed without merging**
