### PR TITLE
RYA-11 initial implementation of free text for mongo backend

### PR DESCRIPTION
**Pull request by pujav65**
Initial implementation.  Mongo backed free text query does not match Accumulo, but I don't have the cycles to finish that.  Updating this so that it matches would be a good future task for someone to pick up.

### CODE REVIEW

**Comment by pujav65** [comment]
Added fixes for Rya-34 to this pull.  Sorry for multiple bugs on the same PR, had to build on fixes from the original pull request

**Comment by amihalik** [comment]
If you fix the conflicts below, I'll merge your PR:

```
CONFLICT (content): Merge conflict in extras/indexingExample/src/main/java/MongoRyaDirectExample.java
CONFLICT (content): Merge conflict in extras/indexing/src/test/java/mvm/rya/indexing/external/PrecompJoinOptimizerIntegrationTest.java
CONFLICT (modify/delete): extras/indexing/src/test/java/mvm/rya/indexing/external/AccumuloIndexSetTest2.java deleted in 13de8a5645391b65ba0a6753eedbb51bff4d7bee and modified 
```

**Comment by pujav65** [comment]
Hey Aaron, the merge conflict is fixed now, but I've been having trouble building.  maven can't resolve the updated geomesa dependencies.  Either way, I think it should be good to build, but I was going to ask you or David to check that it built (since you probably have the dependencies from an earlier build and they must have disappeared recently).

**Comment by amihalik** [comment]
committed.

**Pull request closed without merging**
