### PR TITLE
fix-mongo-tests

### PR DESCRIPTION
**Pull request by jdasch**
## Description
MongoGeoTemporalIndexIT and MongoGeoIndexerFilterIT had 5 tests failing between them.
Updated to extend MongoITBase.  Added unique mongoDBs for isolation.

### Tests
MongoGeoTemporalIndexIT and MongoGeoIndexerFilterIT

### Checklist
- [ ] Code Review
- [ ] Squash Commits

#### People To Reivew
@amihalik 
@meiercaleb

### CODE REVIEW

**Comment by jdasch** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/396/<h2>Build result: FAILURE</span></h2>[...truncated 390.63 KB...][INFO] Apache Rya Spark Support ........................... SKIPPED[INFO] Apache Rya Web Projects ............................ SKIPPED[INFO] Apache Rya Web Implementation ...................... SKIPPED[INFO] ------------------------------------------------------------------------[INFO] BUILD FAILURE[INFO] ------------------------------------------------------------------------[INFO] Total time: 04:24 min[INFO] Finished at: 2017-08-15T20:43:20+00:00[INFO] Final Memory: 129M/3051M[INFO] ------------------------------------------------------------------------[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4.1:single (make-assembly) on project rya.pcj.fluo.app: Failed to create assembly: Error creating assembly archive jar-with-dependencies: Error finalizing component-set for archive. Reason: Permission denied -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException[ERROR] [ERROR] After correcting the problems, you can resume the build with the command[ERROR]   mvn <goals> -rf :rya.pcj.fluo.appchannel stoppedSetting status of b2303f7705304851d800f864cb0d46345dac827c to FAILURE with url https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/396/ and message: 'FAILURE 'Using context: Jenkins: clean package -Pgeoindexing

**Comment by jdasch** [comment]
asfbot build

**Comment by jdasch** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/397/<h2>Build result: FAILURE</span></h2>[...truncated 390.30 KB...][INFO] Apache Rya Spark Support ........................... SKIPPED[INFO] Apache Rya Web Projects ............................ SKIPPED[INFO] Apache Rya Web Implementation ...................... SKIPPED[INFO] ------------------------------------------------------------------------[INFO] BUILD FAILURE[INFO] ------------------------------------------------------------------------[INFO] Total time: 04:38 min[INFO] Finished at: 2017-08-15T20:51:51+00:00[INFO] Final Memory: 128M/3239M[INFO] ------------------------------------------------------------------------[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4.1:single (make-assembly) on project rya.pcj.fluo.app: Failed to create assembly: Error creating assembly archive jar-with-dependencies: Error finalizing component-set for archive. Reason: Permission denied -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException[ERROR] [ERROR] After correcting the problems, you can resume the build with the command[ERROR]   mvn <goals> -rf :rya.pcj.fluo.appchannel stoppedSetting status of b2303f7705304851d800f864cb0d46345dac827c to FAILURE with url https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/397/ and message: 'FAILURE 'Using context: Jenkins: clean package -Pgeoindexing

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/398/<h2>Build result: FAILURE</span></h2>[...truncated 385.36 KB...][INFO] Apache Rya Spark Support ........................... SKIPPED[INFO] Apache Rya Web Projects ............................ SKIPPED[INFO] Apache Rya Web Implementation ...................... SKIPPED[INFO] ------------------------------------------------------------------------[INFO] BUILD FAILURE[INFO] ------------------------------------------------------------------------[INFO] Total time: 05:05 min[INFO] Finished at: 2017-08-15T20:56:45+00:00[INFO] Final Memory: 129M/3053M[INFO] ------------------------------------------------------------------------[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4.1:single (make-assembly) on project rya.pcj.fluo.app: Failed to create assembly: Error creating assembly archive jar-with-dependencies: Error finalizing component-set for archive. Reason: Permission denied -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException[ERROR] [ERROR] After correcting the problems, you can resume the build with the command[ERROR]   mvn <goals> -rf :rya.pcj.fluo.appchannel stoppedSetting status of b2303f7705304851d800f864cb0d46345dac827c to FAILURE with url https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/398/ and message: 'FAILURE 'Using context: Jenkins: clean package -Pgeoindexing

**Comment by jdasch** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/399/

**Pull request closed without merging**
