### PR TITLE
RYA-284: updated to support the use of bloom filter

### PR DESCRIPTION
**Pull request by thn-w**
## Description
Updated dao/accumulo.rya to support the use of bloom filter

### Tests
No new tests

### Links
[JIRA -> RYA-284](https://issues.apache.org/jira/browse/RYA-284R)

#### People To Reivew
@amihalik

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by amihalik** [comment]
I'm seeing some new tests errors and failures when I try to build this PR on my machine.  I'll have asfbot build this on b.a.o.

**Comment by amihalik** [comment]
asfbot build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/<h2>Failed Tests: <span class='status-failure'>21</span></h2><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.indexing' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.indexing/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.indexing</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.indexing/testReport/org.apache.rya.indexing.statement.metadata/AccumuloStatementMetadataNodeTest/simpleQueryWithVariableContextAndJoinOnContext/'><strong>org.apache.rya.indexing.statement.metadata.AccumuloStatementMetadataNodeTest.simpleQueryWithVariableContextAndJoinOnContext</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.indexing/testReport/org.apache.rya.indexing.statement.metadata/AccumuloStatementMetadataNodeTest/simpleQueryWithConstantContext/'><strong>org.apache.rya.indexing.statement.metadata.AccumuloStatementMetadataNodeTest.simpleQueryWithConstantContext</strong></a></li></ul><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.merger' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.merger/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.merger</a>: <span class='status-failure'>6</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.merger/testReport/org.apache.rya.accumulo.mr.merge/RulesetCopyIT/testRulesetCopyTool/'><strong>org.apache.rya.accumulo.mr.merge.RulesetCopyIT.testRulesetCopyTool</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.merger/testReport/org.apache.rya.accumulo.mr.merge/RulesetCopyIT/testRulesetCopyHierarchy/'><strong>org.apache.rya.accumulo.mr.merge.RulesetCopyIT.testRulesetCopyHierarchy</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.merger/testReport/org.apache.rya.accumulo.mr.merge/RulesetCopyIT/testRulesetCopySameAs/'><strong>org.apache.rya.accumulo.mr.merge.RulesetCopyIT.testRulesetCopySameAs</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.merger/testReport/org.apache.rya.accumulo.mr.merge/RulesetCopyIT/testRulesetCopyTransitive/'><strong>org.apache.rya.accumulo.mr.merge.RulesetCopyIT.testRulesetCopyTransitive</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.merger/testReport/org.apache.rya.accumulo.mr.merge/RulesetCopyIT/testRulesetCopyInverse/'><strong>org.apache.rya.accumulo.mr.merge.RulesetCopyIT.testRulesetCopyInverse</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.merger/testReport/org.apache.rya.accumulo.mr.merge/RulesetCopyIT/testRulesetCopySymmetry/'><strong>org.apache.rya.accumulo.mr.merge.RulesetCopyIT.testRulesetCopySymmetry</strong></a></li></ul><h3><a name='incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.sail' /><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport'>incubator-rya-master-with-optionals-pull-requests/org.apache.rya:rya.sail</a>: <span class='status-failure'>13</span></h3><ul><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testSimpleMergeJoinMultiWay/'><strong>org.apache.rya.MergeJoinTest.testSimpleMergeJoinMultiWay</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testMergeJoinMultiWay/'><strong>org.apache.rya.MergeJoinTest.testMergeJoinMultiWay</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya/MergeJoinTest/testSimpleMergeJoin/'><strong>org.apache.rya.MergeJoinTest.testSimpleMergeJoin</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreConnectionTest/testNamedGraphLoad/'><strong>org.apache.rya.RdfCloudTripleStoreConnectionTest.testNamedGraphLoad</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreConnectionTest/testSPOObjRange/'><strong>org.apache.rya.RdfCloudTripleStoreConnectionTest.testSPOObjRange</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testHeartbeatCounts/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testHeartbeatCounts</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testEventsBtwnSystems/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testEventsBtwnSystems</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testAllEvents/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testAllEvents</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya/RdfCloudTripleStoreTest/testEventsForUri/'><strong>org.apache.rya.RdfCloudTripleStoreTest.testEventsForUri</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya.rdftriplestore.evaluation/StatementPatternEvalTest/simpleQueryWithBindingSetConstantContext/'><strong>org.apache.rya.rdftriplestore.evaluation.StatementPatternEvalTest.simpleQueryWithBindingSetConstantContext</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya.rdftriplestore.evaluation/StatementPatternEvalTest/simpleQueryNoBindingSetConstantContext/'><strong>org.apache.rya.rdftriplestore.evaluation.StatementPatternEvalTest.simpleQueryNoBindingSetConstantContext</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya.rdftriplestore.evaluation/StatementPatternEvalTest/simpleQueryWithBindingSetSameContext/'><strong>org.apache.rya.rdftriplestore.evaluation.StatementPatternEvalTest.simpleQueryWithBindingSetSameContext</strong></a></li><li><a href='https://builds.apache.org/job/incubator-rya-master-with-optionals-pull-requests/229/org.apache.rya$rya.sail/testReport/org.apache.rya.rdftriplestore.evaluation/StatementPatternEvalTest/simpleQueryWithoutBindingSets/'><strong>org.apache.rya.rdftriplestore.evaluation.StatementPatternEvalTest.simpleQueryWithoutBindingSets</strong></a></li></ul>

**Comment by pujav65** [comment]
@thn-w , can you address the test failures?

**Comment by thn-w** [comment]
The error is related to "context" (as mentioned by @amihalik)  that was added. I don't have enough knowledge to address the test failures related to context at all.

**Pull request closed without merging**
