### PR TITLE
Fixing merge conflict with Feature/spark graph x

### PR DESCRIPTION
**Pull request by pujav65**
This is a redo of an existing pull request that had a merge conflict.  The merge request provided spark and graphx support for rya.

tests were written for new classes

### Links
[Jira](https://issues.apache.org/jira/browse/RYA-NUMBER)

### Checklist
- [ ] Code Review
- [ ] Squash Commits

#### People To Reivew
@jessehatfield please make sure i resolved the conflict correctly

### CODE REVIEW

**Comment by pujav65** [comment]
asfbot build

**Comment by amihalik** [comment]
@pujav65 Looks like an error with the pom.  Still referencing an old version of Rya?

[FATAL] Non-resolvable parent POM: Could not find artifact org.apache.rya:rya-project:pom:3.2.10-incubating-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 24, column 13

**Comment by pujav65** [comment]
asfbot build

**Comment by pujav65** [comment]
@amihalik I saw -- kicked off a new build after pushing to github, it should pass now i think

**Pull request closed without merging**
