### PR TITLE
RYA-323 Enabling Multi Var Geo Functions. Closes #183

### PR DESCRIPTION
**Pull request by amihalik**
[Brief Description of what changed]

[Description of what tests were written]

### Links
[Jira](https://issues.apache.org/jira/browse/RYA-323)

### Checklist
- [ ] Code Review
- [ ] Squash Commits

#### People To Reivew
@meiercaleb

### CODE REVIEW

**Comment by amihalik** [comment]
@isper3at Can you look at this too. This PR is required to enable one of the main use cases for the geo:nearby function that you're working on

**Comment by isper3at** [comment]
I didn't have any issue getting multi-var Near to work without this fix

**Comment by amihalik** [comment]
@isper3at I can't wait to see your PR 

We might still need my PR to do a multi-var geo:equals.  Although I wouldn't doubt that you fixed that as well. :+1:

**Comment by isper3at** [comment]
I just did an argument count check where if(args>2) gets ignored if it's Near() so it's hardly clean.  if I took that check out, all the args came back as Values.

**Comment by pujav65** [comment]
checking build and will then merge

**Comment by pujav65** [comment]
wait, just read the comment chain -- is this pr obe @amihalik @isper3at ?

**Comment by amihalik** [comment]
@pujav65 yeah puja hold off on merging any of these PRs until we get the build sorted.  we'll test out @isper3at's #187 and #186 PRs first, then determine if need this PR.

**Pull request closed without merging**
